name: workflow1
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: step1
            run: echo "Helow Padmanabha"

          - name: step2
            run: echo "First workkflow created"
